### PR TITLE
494 fe content panel bug tags

### LINKED ISSUE #494: [FE] Content-Panel: Bug: Tags
Regardless if the user is in edit mode or not, tags can be added. 
We need to check the role of the logged in user, because only admins should be able to create new tags.

### PR DESCRIPTION
**Pull request by mitkapanarin**
Tag Management Requirements:

Both content managers and admins can add existing tags
Only admins can create new tags
All operations require edit mode

### CODE REVIEW

File: apis/mutations/blogs/useAddNewPost.ts [hunk 1]
```diff
@@ -33,8 +33,12 @@ const useAddNewPost = () => {
       toast.error(error?.response?.data?.message || 'Настана грешка при креирање на статијата.');
     },
     onSuccess: () => {
-      queryClient.invalidateQueries({ queryKey: QUERY_KEYS.BLOGS.ALL });
       toast.success('Статијата беше успешно објавена!');
+      onSuccess?.();
+      // Invalidate queries after showing success message
+      setTimeout(() => {
+        queryClient.invalidateQueries({ queryKey: QUERY_KEYS.BLOGS.ALL });
+      }, 100);
```
Comment (dichoskaemilija) [inline apis/mutations/blogs/useAddNewPost.ts]: You dont need to call setTimeout inside onSucess. Follow the pattern bellow:
export const useAddNewPost = () => {
  const queryClient = useQueryClient();
  return useMutation((params: Params) => addNewPost(params), {
    onSuccess: (_, variables) => {
//Here the query key should be the one from the get blog posts query
      queryClient.invalidateQueries({ queryKey: ["newPost"] });
    },
  });

File: apis/mutations/blogs/useEditBlogPost.ts [hunk 2]
```diff
@@ -45,8 +46,12 @@ const useEditBlogPost = () => {
       toast.error(error?.response?.data?.message || 'Настана грешка при ажурирање на статијата.');
     },
     onSuccess: () => {
-      queryClient.invalidateQueries({ queryKey: QUERY_KEYS.BLOGS.ALL });
       toast.success('Статијата беше успешно ажурирана!');
+      onSuccess?.();
+      // Invalidate queries after showing success message
+      setTimeout(() => {
+        queryClient.invalidateQueries({ queryKey: QUERY_KEYS.BLOGS.ALL });
+      }, 100);
```
Comment (dichoskaemilija) [inline apis/mutations/blogs/useEditBlogPost.ts]: same from above

File: apis/mutations/blogs/useEditBlogPost.ts [hunk 3]
```diff
@@ -20,21 +20,22 @@ type ErrorResponse = {
...
+      const [editResponse, statusResponse] = await Promise.all([
+        axios.patch(ENDPOINTS.BLOGS.EDIT(id), {
+          title,
+          content,
+          tags,
+        }),
+        axios.patch(`${ENDPOINTS.BLOGS.UPDATE_STATUS(id)}`, {
+          status,
+        }),
+      ]);
```
Comment (dichoskaemilija) [inline apis/mutations/blogs/useEditBlogPost.ts]: what happens id the user doesn't update the status? we shouldnt make the second call in that scenario

File: apis/mutations/blogs/useEditBlogPost.ts [hunk 4]
```diff
@@ -20,21 +20,22 @@ type ErrorResponse = {
   statusCode?: number;
 };
 
-const useEditBlogPost = () => {
+const useEditBlogPost = (onSuccess?: () => void) => {
```
Comment (dichoskaemilija) [inline apis/mutations/blogs/useEditBlogPost.ts]: Is there a reason we are accepting onSuccess as a parametar here?
the useEditBlogPost handles the onSuccess inside it. It returns isSuccess value.

File: components/module-components/blog/PublishArticleForm.tsx [hunk 5]
```diff
@@ -1,21 +1,32 @@
...
+  const isAdmin = session?.user?.role === UserRole.admin;
   const router = useRouter();
+  const tagManagerRef = useRef<TagManagerRef>(null);
+  const [selectedTags, setSelectedTags] = useState<Tag[]>([]);
+  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
+
+  const addNewPostMutation = useAddNewPost(() => {
+    setHasUnsavedChanges(false);
+    router.push('/content-panel/blogs');
+  });
```
Comment (dichoskaemilija) [inline components/module-components/blog/PublishArticleForm.tsx]: Here you can use the following pattern:
call the addNewPostMutation mutation, on Success handle the    
setHasUnsavedChanges(false);
router.push('/content-panel/blogs');

on Error display a toast with the error

File: components/module-components/blog/TagInput.tsx [hunk 6]
```diff
@@ -12,20 +12,38 @@ import { Tag } from '../../reusable-components/_Types';
...
+  const { selectedTags, onTagsChange, isAdmin = false, isEditMode = false } = props;
   const [searchTag, setSearchTag] = useState<string>('');
   const debouncedSearchTerm = useDebounce(searchTag, 300);
   const { data } = useGetTags(debouncedSearchTerm);
   const addNewTagMutation = useAddNewTag();
 
+  useImperativeHandle(ref, () => ({
+    clearInput: () => setSearchTag(''),
+  }));
+
```
Comment (dichoskaemilija) [inline components/module-components/blog/TagInput.tsx]: What is the purpose of useImperativeHandle?

**Review by dichoskaemilija — CHANGES_REQUESTED** [review]
Great start! Just a few improvements suggested.
Can you please go through all the changed files and remove the comments 🙏

File: components/module-components/blog/PublishArticleForm.tsx [hunk 7]
```diff
@@ -1,21 +1,32 @@
...
+  const { data: session } = useSession();
+  const isAdmin = session?.user?.role === UserRole.admin;
   const router = useRouter();
+  const tagManagerRef = useRef<TagManagerRef>(null);
+  const [selectedTags, setSelectedTags] = useState<Tag[]>([]);
+  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
+
+  const addNewPostMutation = useAddNewPost(() => {
+    setHasUnsavedChanges(false);
+    router.push('/content-panel/blogs');
```
Comment (dichoskaemilija) [inline components/module-components/blog/PublishArticleForm.tsx]: here you can handle onSuccess and onError and return appropriate toast messages.
So you can follow the following pattern:
First define the mutation: const {mutate: addNewPost}= useAddNewPost()
So onSuccess => do this:
  const addNewPostMutation = (arguments) => {

    useAddNewPost(
      {
       arguments
      },
      {
        onSuccess: () => {
    setHasUnsavedChanges(false);
    router.push('/content-panel/blogs');
        },
        onError: (error: any) => {
    //show a toast 
        },
      },
    );
  };
  
 **This way the mutation hook will remain reusable and the side effects are localized**

File: components/module-components/blog/PublishArticleForm.tsx [hunk 8]
```diff
@@ -31,119 +42,189 @@ const PublishArticleForm = () => {
...
+      }
+      return undefined;
+    };
+
+    window.addEventListener('beforeunload', handleBeforeUnload);
+    return () => window.removeEventListener('beforeunload', handleBeforeUnload);
+  }, [hasUnsavedChanges]);
+
   const handleAddPost = (values: NewPost) => {
+    setHasUnsavedChanges(false); // Reset immediately since we're about to save
```
Comment (dichoskaemilija) [inline components/module-components/blog/PublishArticleForm.tsx]: remove comment

**Review by dichoskaemilija — CHANGES_REQUESTED** [review]

File: components/module-components/blog/TagInput.tsx (hunk 6 above)
Comment (mitkapanarin) [reply components/module-components/blog/TagInput.tsx]: Removed useImperativeHandle by lifting searchTag state to TagManager for better state management

**Review by dichoskaemilija — APPROVED** [review]
great work @mitkapanarin 👏
